export * from './Animation';
export * from './Audio';
export * from './BackgroundFill';
export * from './BackgroundFillFreeformGradient';
export * from './BackgroundFillGradient';
export * from './BackgroundFillSolid';
export * from './BackgroundType';
export * from './BackgroundTypeChatTheme';
export * from './BackgroundTypeFill';
export * from './BackgroundTypePattern';
export * from './BackgroundTypeWallpaper';
export * from './Birthdate';
export * from './BotCommand';
export * from './BotCommandScope';
export * from './BotCommandScopeAllChatAdministrators';
export * from './BotCommandScopeAllGroupChats';
export * from './BotCommandScopeAllPrivateChats';
export * from './BotCommandScopeChat';
export * from './BotCommandScopeChatAdministrators';
export * from './BotCommandScopeChatMember';
export * from './BotCommandScopeDefault';
export * from './BotDescription';
export * from './BotName';
export * from './BotShortDescription';
export * from './BusinessConnection';
export * from './BusinessIntro';
export * from './BusinessLocation';
export * from './BusinessMessagesDeleted';
export * from './BusinessOpeningHours';
export * from './BusinessOpeningHoursInterval';
export * from './CallbackGame';
export * from './CallbackQuery';
export * from './Chat';
export * from './ChatAdministratorRights';
export * from './ChatBackground';
export * from './ChatBoost';
export * from './ChatBoostAdded';
export * from './ChatBoostRemoved';
export * from './ChatBoostSource';
export * from './ChatBoostSourceGiftCode';
export * from './ChatBoostSourceGiveaway';
export * from './ChatBoostSourcePremium';
export * from './ChatBoostUpdated';
export * from './ChatFullInfo';
export * from './ChatInviteLink';
export * from './ChatJoinRequest';
export * from './ChatLocation';
export * from './ChatMember';
export * from './ChatMemberAdministrator';
export * from './ChatMemberBanned';
export * from './ChatMemberLeft';
export * from './ChatMemberMember';
export * from './ChatMemberOwner';
export * from './ChatMemberRestricted';
export * from './ChatMemberUpdated';
export * from './ChatPermissions';
export * from './ChatPhoto';
export * from './ChatShared';
export * from './ChosenInlineResult';
export * from './Contact';
export * from './Dice';
export * from './Document';
export * from './EncryptedCredentials';
export * from './EncryptedPassportElement';
export * from './ExternalReplyInfo';
export * from './File';
export * from './ForceReply';
export * from './ForumTopic';
export * from './ForumTopicClosed';
export * from './ForumTopicCreated';
export * from './ForumTopicEdited';
export * from './ForumTopicReopened';
export * from './Game';
export * from './GameHighScore';
export * from './GeneralForumTopicHidden';
export * from './GeneralForumTopicUnhidden';
export * from './Giveaway';
export * from './GiveawayCompleted';
export * from './GiveawayCreated';
export * from './GiveawayWinners';
export * from './InaccessibleMessage';
export * from './index';
export * from './InlineKeyboardButton';
export * from './InlineKeyboardMarkup';
export * from './InlineQuery';
export * from './InlineQueryResult';
export * from './InlineQueryResultArticle';
export * from './InlineQueryResultAudio';
export * from './InlineQueryResultCachedAudio';
export * from './InlineQueryResultCachedDocument';
export * from './InlineQueryResultCachedGif';
export * from './InlineQueryResultCachedMpeg4Gif';
export * from './InlineQueryResultCachedPhoto';
export * from './InlineQueryResultCachedSticker';
export * from './InlineQueryResultCachedVideo';
export * from './InlineQueryResultCachedVoice';
export * from './InlineQueryResultContact';
export * from './InlineQueryResultDocument';
export * from './InlineQueryResultGame';
export * from './InlineQueryResultGif';
export * from './InlineQueryResultLocation';
export * from './InlineQueryResultMpeg4Gif';
export * from './InlineQueryResultPhoto';
export * from './InlineQueryResultsButton';
export * from './InlineQueryResultVenue';
export * from './InlineQueryResultVideo';
export * from './InlineQueryResultVoice';
export * from './InputContactMessageContent';
export * from './InputFile';
export * from './InputInvoiceMessageContent';
export * from './InputLocationMessageContent';
export * from './InputMedia';
export * from './InputMediaAnimation';
export * from './InputMediaAudio';
export * from './InputMediaDocument';
export * from './InputMediaPhoto';
export * from './InputMediaVideo';
export * from './InputMessageContent';
export * from './InputPaidMedia';
export * from './InputPaidMediaPhoto';
export * from './InputPaidMediaVideo';
export * from './InputPollOption';
export * from './InputSticker';
export * from './InputTextMessageContent';
export * from './InputVenueMessageContent';
export * from './Invoice';
export * from './KeyboardButton';
export * from './KeyboardButtonPollType';
export * from './KeyboardButtonRequestChat';
export * from './KeyboardButtonRequestUsers';
export * from './LabeledPrice';
export * from './LinkPreviewOptions';
export * from './Location';
export * from './LoginUrl';
export * from './MaskPosition';
export * from './MaybeInaccessibleMessage';
export * from './MenuButton';
export * from './MenuButtonCommands';
export * from './MenuButtonDefault';
export * from './MenuButtonWebApp';
export * from './Message';
export * from './MessageAutoDeleteTimerChanged';
export * from './MessageEntity';
export * from './MessageId';
export * from './MessageOrigin';
export * from './MessageOriginChannel';
export * from './MessageOriginChat';
export * from './MessageOriginHiddenUser';
export * from './MessageOriginUser';
export * from './MessageReactionCountUpdated';
export * from './MessageReactionUpdated';
export * from './OrderInfo';
export * from './PaidMedia';
export * from './PaidMediaInfo';
export * from './PaidMediaPhoto';
export * from './PaidMediaPreview';
export * from './PaidMediaVideo';
export * from './PassportData';
export * from './PassportElementError';
export * from './PassportElementErrorDataField';
export * from './PassportElementErrorFile';
export * from './PassportElementErrorFiles';
export * from './PassportElementErrorFrontSide';
export * from './PassportElementErrorReverseSide';
export * from './PassportElementErrorSelfie';
export * from './PassportElementErrorTranslationFile';
export * from './PassportElementErrorTranslationFiles';
export * from './PassportElementErrorUnspecified';
export * from './PassportFile';
export * from './PhotoSize';
export * from './Poll';
export * from './PollAnswer';
export * from './PollOption';
export * from './PreCheckoutQuery';
export * from './ProximityAlertTriggered';
export * from './ReactionCount';
export * from './ReactionType';
export * from './ReactionTypeCustomEmoji';
export * from './ReactionTypeEmoji';
export * from './ReplyKeyboardMarkup';
export * from './ReplyKeyboardRemove';
export * from './ReplyParameters';
export * from './ResponseParameters';
export * from './SentWebAppMessage';
export * from './SharedUser';
export * from './ShippingAddress';
export * from './ShippingOption';
export * from './ShippingQuery';
export * from './StarTransaction';
export * from './StarTransactions';
export * from './Sticker';
export * from './StickerSet';
export * from './Story';
export * from './SuccessfulPayment';
export * from './SwitchInlineQueryChosenChat';
export * from './TextQuote';
export * from './PaidMedia';
export * from './PaidMediaInfo';
export * from './PaidMediaPhoto';
export * from './PaidMediaPreview';
export * from './PaidMediaVideo';
export * from './TransactionPartnerUser';
export * from './Update';
export * from './User';
export * from './UserProfilePhotos';
export * from './UsersShared';
export * from './Venue';
export * from './Video';
export * from './VideoChatEnded';
export * from './VideoChatParticipantsInvited';
export * from './VideoChatScheduled';
export * from './VideoChatStarted';
export * from './VideoNote';
export * from './Voice';
export * from './WebAppData';
export * from './WebAppInfo';
export * from './WebhookInfo';
export * from './WriteAccessAllowed';

import { ResponseParameters } from './ResponseParameters';

/**
 * @see https://core.telegram.org/bots/api#making-requests
 */

export type SuccessResponse = {
  ok: true;
  result: unknown;
  description?: string;
};
export type ErrorResponse = {
  ok: false;
  description: string;
  error_code: number;
  parameters?: ResponseParameters;
};
export type Response = SuccessResponse | ErrorResponse;

/**
 * ## Formatting options
 * @see https://core.telegram.org/bots/api#formatting-options
 */
export type ParseMode = 'Markdown' | 'MarkdownV2' | 'HTML';
